-- LaunchTerminal Initial Migration
-- Generated by drizzle-kit

CREATE TABLE IF NOT EXISTS "conversations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "user_id" text NOT NULL,
  "platform" text NOT NULL,
  "channel_id" text NOT NULL,
  "started_at" timestamp DEFAULT now() NOT NULL,
  "last_message_at" timestamp DEFAULT now() NOT NULL,
  "message_count" integer DEFAULT 0 NOT NULL,
  "metadata" jsonb
);

CREATE TABLE IF NOT EXISTS "messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "conversation_id" uuid NOT NULL REFERENCES "conversations"("id"),
  "role" text NOT NULL,
  "content" text NOT NULL,
  "platform" text NOT NULL,
  "user_id" text NOT NULL,
  "token_count" integer,
  "latency_ms" integer,
  "blocked" boolean DEFAULT false NOT NULL,
  "block_reason" text,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "plugins" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "name" text UNIQUE NOT NULL,
  "version" text NOT NULL,
  "enabled" boolean DEFAULT true NOT NULL,
  "config" jsonb,
  "installed_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "api_keys" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "key_hash" text UNIQUE NOT NULL,
  "permissions" jsonb DEFAULT '[]' NOT NULL,
  "rate_limit" integer DEFAULT 100,
  "last_used_at" timestamp,
  "expires_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "revoked" boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS "audit_log" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "action" text NOT NULL,
  "actor" text NOT NULL,
  "resource" text NOT NULL,
  "resource_id" text,
  "details" jsonb,
  "ip" text,
  "timestamp" timestamp DEFAULT now() NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS "conversations_user_id_idx" ON "conversations" ("user_id");
CREATE INDEX IF NOT EXISTS "conversations_platform_idx" ON "conversations" ("platform");
CREATE INDEX IF NOT EXISTS "messages_conversation_id_idx" ON "messages" ("conversation_id");
CREATE INDEX IF NOT EXISTS "messages_user_id_idx" ON "messages" ("user_id");
CREATE INDEX IF NOT EXISTS "messages_created_at_idx" ON "messages" ("created_at");
CREATE INDEX IF NOT EXISTS "audit_log_action_idx" ON "audit_log" ("action");
CREATE INDEX IF NOT EXISTS "audit_log_actor_idx" ON "audit_log" ("actor");
CREATE INDEX IF NOT EXISTS "audit_log_timestamp_idx" ON "audit_log" ("timestamp");
